import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import useAxios from "axios-hooks";
import { financialReport } from "../config/urlMAS";
import { Button, Container } from "@mui/material";

const Home: NextPage = () => {
  const [{ data, loading, error }] = useAxios(
    financialReport("HDC", "CDKT", "Y", "2022")
  );

  if (loading) return <p>Loading...</p>;
  if (error) return <p>Error!</p>;
  return (
    <div>
      <Head>
        <title>StockToo</title>
        <meta name="description" content="Generated by StockToo" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        {/* <pre>{JSON.stringify(data, null, 2)}</pre> */}
        <h1>So Sánh</h1>
        <Button variant="text">Text</Button>
        <Button variant="contained">Contained</Button>
        <Button variant="outlined">Outlined</Button>
      </Container>
    </div>
  );
};

export default Home;
